engines:
  haxe-checkstyle:
    enabled: true
    checks:
      MagicNumber:
        enabled: false

exclude_paths:
  - dox/**/*

ratings:
  paths:
    - "geometrize"
  exclude_paths:
    - "docs/geometrize"